USE [BancoConta]
GO

/****** Object:  Table [dbo].[Contas]    Script Date: 04/12/2023 21:55:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Contas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Titular] [nvarchar](100) NULL,
	[Saldo] [decimal](18, 2) NULL,
 CONSTRAINT [PK__Contas__3214EC0732B5573C] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

